CreateThread(Plb.Init)
RegisterNetEvent("plouffe_paletobank:sendConfig",Plb.LoadPlayer)
RegisterNetEvent("plouffe_paletobank:removeItem",  Plb.RemoveItem)
RegisterNetEvent("plouffe_paletobank:lockpickedDoor", Plb.PlayerUnlockedDoor)
RegisterNetEvent("plouffe_paletobank:hack_succes", Plb.PlayerHackFinished)
RegisterNetEvent("plouffe_paletobank:requestLoots", Plb.RequestLoots)
RegisterNetEvent("plouffe_paletobank:TryDestroyLoots", Plb.DestroyLoots)